### ISSUE TITLE
Issue while converting a shapefile to geojson 

### ISSUE THREAD

**Issue by dhivakar-s** [wavded/ogre#103]
I'm trying to convert a shapefile to geo JSON  but I'm getting an error like this 
`{
  "error": true,
  "message": "Command failed: ogr2ogr -f GeoJSON -skipfailures /vsistdout/ /vsizip//tmp/de48455de7f1216537cc26e76e53767cMS4S (2).zip\nFAILURE:\nUnable to open datasource `/vsizip//tmp/de48455de7f1216537cc26e76e53767cMS4S (2).zip' with the following drivers.\n  -> `FITS'\n  -> `PCIDSK'\n  -> `netCDF'\n  -> `PDS4'\n  -> `VICAR'\n  -> `JP2OpenJPEG'\n  -> `PDF'\n  -> `MBTiles'\n  -> `BAG'\n  -> `EEDA'\n  -> `OGCAPI'\n  -> `ESRI Shapefile'\n  -> `MapInfo File'\n  -> `UK .NTF'\n  -> `LVBAG'\n  -> `OGR_SDTS'\n  -> `S57'\n  -> `DGN'\n  -> `OGR_VRT'\n  -> `REC'\n  -> `Memory'\n  -> `BNA'\n  -> `CSV'\n  -> `NAS'\n  -> `GML'\n  -> `GPX'\n  -> `LIBKML'\n  -> `KML'\n  -> `GeoJSON'\n  -> `GeoJSONSeq'\n  -> `ESRIJSON'\n  -> `TopoJSON'\n  -> `Interlis 1'\n  -> `Interlis 2'\n  -> `OGR_GMT'\n  -> `GPKG'\n  -> `SQLite'\n  -> `OGR_DODS'\n  -> `ODBC'\n  -> `WAsP'\n  -> `PGeo'\n  -> `MSSQLSpatial'\n  -> `OGR_OGDI'\n  -> `PostgreSQL'\n  -> `MySQL'\n  -> `OpenFileGDB'\n  -> `XPlane'\n  -> `DXF'\n  -> `CAD'\n  -> `FlatGeobuf'\n  -> `Geoconcept'\n  -> `GeoRSS'\n  -> `GPSTrackMaker'\n  -> `VFK'\n  -> `PGDUMP'\n  -> `OSM'\n  -> `GPSBabel'\n  -> `SUA'\n  -> `OpenAir'\n  -> `OGR_PDS'\n  -> `WFS'\n  -> `OAPIF'\n  -> `SOSI'\n  -> `HTF'\n  -> `AeronavFAA'\n  -> `Geomedia'\n  -> `EDIGEO'\n  -> `SVG'\n  -> `CouchDB'\n  -> `Cloudant'\n  -> `Idrisi'\n  -> `ARCGEN'\n  -> `SEGUKOOA'\n  -> `SEGY'\n  -> `XLS'\n  -> `ODS'\n  -> `XLSX'\n  -> `Elasticsearch'\n  -> `Walk'\n  -> `Carto'\n  -> `AmigoCloud'\n  -> `SXF'\n  -> `Selafin'\n  -> `JML'\n  -> `PLSCENES'\n  -> `CSW'\n  -> `VDV'\n  -> `GMLAS'\n  -> `MVT'\n  -> `NGW'\n  -> `MapML'\n  -> `TIGER'\n  -> `AVCBin'\n  -> `AVCE00'\n  -> `HTTP'\n"
}`

Any help will be appreciated

**Comment by wavded** [comment]
Are the shapefile contents at the root of the zip file?
