### ISSUE TITLE
stdout maxBuffer length exceeded 

### ISSUE THREAD

**Issue by mohammadrezaataeii** [wavded/ogre#107]
Hi when i  upload a file over than 20MB, 
i get error code 500, with this  message : 
![error](https://user-images.githubusercontent.com/90499633/200813655-f1690394-1729-42f1-98ba-867b1d564198.png)

what should i do ? please let me

**Comment by wavded** [comment]
please provide more details on how you are using Ogre, public? hosted? config options? etc.

**Comment by mohammadrezaataeii** [comment]
i uploaded my shapefile.zip with more than 20MB

Here is my func : 
const addShapeFile = (file) => {
    const formData = new FormData();
    formData.append("upload", file);
    fetch("http://ogre.adc4gis.com/convert", {
      method: "POST",
      body: formData,
    })
      .then((res) => res.json())
      .then((responseData) => {
        setGeoData(responseData);  
      });
  };

**Comment by wavded** [comment]
This issue should be addressed now in v3.0.4, thx for reporting.
