### ISSUE TITLE
POst request

### ISSUE THREAD

**Issue by ghost** [wavded/ogre#27]
Hi,

Trying to directly make an HTTP POST request and get this as a response:

{"error":true,"msg":"Cannot read property 'upload' of undefined"}

I'm providing the upload parameter with the local file location.

**Comment by sudheerpitchika** [comment]
I am trying to use ogre convert in my application, and calling this service from client side.
I am trying to use OGRE online converter to convert shapefiles to different format, referring https://ogre.adc4gis.com/ I am making an AJAX call to send the file and get the response, but the response says "Cannot read property 'path' of undefined"

Below is the code snippet for ajax call, where sFile is the file from the file upload control. I tried to attach file in several methods for 'data' in ajax call (create FormData object, creating object etc), but I am getting the same error.

    function shapeFileProcessing(sFile){

         var formdata = new FormData();
         formdata.append("upload", sFile);

         var obj = {};
         obj.upload = sFile;

           $.ajax({
                  url : 'http://ogre.adc4gis.com/convert',
                  data : obj,
                  type : "POST",
                  success : function(msg) {
                    console.log("Success: "+msg);
                  }
          });
    }

I also tried with a form and submitting as it is in https://ogre.adc4gis.com/ but the result is redirecting to https://ogre.adc4gis.com/convert even if I have jsonpcallback. 
How can I use this in my client side application using ajax call?

Thanks in advance
