### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by ghost** [wavded/ogre#34]
Hi :)

As part of my app, I convert GeoJson files into Shapefiles. The tool worked great before v0.8.0, but it is giving me this error message after and including v0.8.0:
{"error":true,"msg":"request entity too large"}

The json file itself is quite large but it used to convert successfully. Any ideas why this issue might be happening?

Thanks!

**Comment by Jigeeshu** [comment]
How many MB of geojson does it support
