### ISSUE TITLE
Support for precision

### ISSUE THREAD

**Issue by letmaik** [wavded/ogre#43]
In this blog post http://blog.thematicmapping.org/2012/11/how-to-minify-geojson-files.html it is described how to set the precision of the geojson coordinates, only keeping 1 decimal for example. This would be a really useful option in the web tool! :)

**Comment by DarinMacRae** [comment]
It seems simple enough to add an additional form box and pass on to the _-lco COORDINATE_PRECISION=n_ parameter.

It would allow saving massive amounts of bandwidth on the response.
