### ISSUE TITLE
Add page to wiki

### ISSUE THREAD

**Issue by btfou** [wavded/ogre#44]
@wavded I added https://github.com/wavded/ogre/wiki/Deploying-Ogre-on-Windows-Server.

Had to doc what I did. Thought I'd add it. Not an issue if you would rather not have it.

Thanks for your work on this!

**Comment by wavded** [comment]
Thanks for the contrib!  Glad you added it.  I mostly work in *nix environment so I'm sure this will help some people out in ways I can't!
