### ISSUE TITLE
Get ERROR #4: Unable to open datasource

### ISSUE THREAD

**Issue by masterflorin** [wavded/ogre#47]
Whenever I try to convert a small shapefile using the ogre web client

`{"errors":["ERROR 4: Unable to open /tmp/27651-kd1jy0.shx or /tmp/27651-kd1jy0.SHX.","FAILURE:","Unable to open datasource`

**Comment by wavded** [comment]
Are you missing a SHX file?  That one is required, along with a DBF and SHP file (PRJ is optional)

**Comment by masterflorin** [comment]
Not really, I have a .shx, .dbf and a .prj besides the .shp.

**Comment by masterflorin** [comment]
Solved. I'm a bit ashamed of myself for even saying this but I didn't uploaded the.zip how I should have. Never mind about my foolishness. Many thanks for answering.
