### ISSUE TITLE
WFS Support

### ISSUE THREAD

**Issue by benehuber** [wavded/ogre#49]
It would be great to use WFS Service URL's as Input instead of GEOJSON or Files. 
WFS2Shape is what I need.

**Comment by wavded** [comment]
Hmm what geospatial server do you have?  Depending on the geospatial server you can get GeoJSON endpoints.

e.g.

http://docs.geoserver.org/latest/en/user/services/wfs/outputformats.html

**Comment by benehuber** [comment]
I know, but we have ESRI Arcgis Server and there you only get GML from WFS Endpoint.

**Comment by wavded** [comment]
Bummer.  The `ogr2ogr` module (which `ogre` is built on) already has support for this use case, we'd just need to make some UI for it in Ogre.  Care to make a pull request?  Otherwise may be able to get to this later this week.

**Comment by benehuber** [comment]
I know that ogr2ogr can handle wfs. Would be great if you can implement some UI for that. One week earlie or later doesn't matter.... Thanks for every Kind of Support
