### ISSUE TITLE
Output displays in the browser, causing the browser to crash preventing download

### ISSUE THREAD

**Issue by alanomaly** [wavded/ogre#52]
I've got a 40mb GML file I'm trying to convert. Ogre does a good job of it - but then instead of letting me download the ~50mb output, it displays it as text in the browser. It doesn't offer any alternative option - there's no "download" tick box or similar I can see.

Browsers aren't designed to display megabytes of text, so the browser crashes every time, and can't save the output. Not only that, but many browsers' save tools cause the page to reload, losing the output, preventing it from being downloaded.

It's a shame to see a tool do a good job then fail at the final hurdle like this.

Can't you set the output to download as a file? Or at least, allow users to choose?

Allowing URL input would be good too.

**Comment by wavded** [comment]
A forceDownload option has been added.
