### ISSUE TITLE
File support

### ISSUE THREAD

**Issue by cagridural** [wavded/ogre#53]
Ogre is already awesome and would be great with DWG, MIF, and DGN V8 support.

**Comment by wavded** [comment]
Ogre uses gdal/ogr2ogr tool under the scenes which doesn't compile DWG support in by default and I don't believe supports MIF.  It does support DGN but perhaps not V8 (not sure what that is).

**Comment by cagridural** [comment]
Gdal/ogr2ogr actually supports MIF via command line.

`C:\Users\CBS>cd` desktop\format conversion test\format files\mif

C:\Users\CBS\Desktop\Format Conversion Test\Format Files\MIF>ogrinfo -al -so mexico.mif
Had to open data source read-only.
INFO: Open of `mexico.mif'
      using driver `MapInfo File' successful.

Layer name: mexico
Geometry: Unknown (any)
Feature Count: 32
Extent: (-117.124638, 14.536945) - (-86.743386, 32.718425)
Layer SRS WKT:
GEOGCS["unnamed",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563],
        TOWGS84[0,0,0,0,0,0,0]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433]]
State_Name: String (35.0)
State_Code: String (8.0)
Pop_90: Real (8.0)
Households_90: Real (8.0)
Cars_91: Real (8.0)
Buses_91: Real (8.0)
Trucks_91: Real (8.0)
Tot_Vehicles_91: Real (8.0)
Area_Miles: Real (10.2)
Area_Km: Real (10.2)

C:\Users\CBS\Desktop\Format Conversion Test\Format Files\MIF>ogr2ogr -f "GeoJSON" mexico.json mexico.mif`

If you can tell me where to place, my colleagues will send a pull request.

**Comment by wavded** [comment]
@cagridural sorry for dropping the ball on this, I didn't recognize your last line about a PR which I would totally welcome.  The PR would need to be submitted for the https://github.com/wavded/ogr2ogr to add the support and to this repo to add the documentation.
