### ISSUE TITLE
Unable to send via .net WebRequest

### ISSUE THREAD

**Issue by evermanwa** [wavded/ogre#54]
I have been pulling my hair out for some time now trying to send over a .net connection. I using the following code below but it keeps coming back with a "bad request" error. I'm not sure what it's having an issue with. Is this an issue with my request format or the webserver?

Example:
                Stream responseStream = response.GetResponseStream();

```
            byte[] rawData = ConvertToByteArray(responseStream);
            using (HttpClient client = new HttpClient())
            {
                using (MultipartFormDataContent formData = new MultipartFormDataContent())
                {
                    formData.Add(new ByteArrayContent(rawData, 0, rawData.Length), "Upload");
                    using (var message = await client.PostAsync("http://ogre.adc4gis.com/convert", formData))
                    {
                        var result = await message.Content.ReadAsStreamAsync();
                    }
                }
            }
```

Any insight or better way to do it would be much appreciated. Thanks!

**Comment by evermanwa** [comment]
My stream I am uploading is a kml file.

**Comment by wavded** [comment]
I do not know .NET so I was hoping someone else with experience would be able to assist you.  Did you find a resolution @evermanwa ?

**Comment by evermanwa** [comment]
Hello wavded,

Sorry it took so long to reply, but yes I eventually tried a different tactic and this worked. Thanks!

Regards,
William

**Comment by evermanwa** [comment]
`                using (WebClient client = new WebClient())
                {
                    var prms = new System.Collections.Specialized.NameValueCollection();
                    prms.Add("json", json);

                    byte[] response = client.UploadValues("http://ogre.adc4gis.com/convertJson", "POST", prms);

                    return response;`
