### ISSUE TITLE
Setting up local environment on Windows

### ISSUE THREAD

**Issue by nivemaham** [wavded/ogre#56]
Hi there,
I found out **ogre** is provided interesting features to support geo formats.
I want to run ogre locally, to do some experiments and developments.

As the first step i tried to set up local environment. I am working on Windows. With no surprises, i got a lot of installation issues.

1) Does **npm install ogre** is enough to do or should i also install **gdal** packages for windows.
There are [many choices available](https://trac.osgeo.org/gdal/wiki/DownloadingGdalBinaries) for windows, which is confusing.

2) I tried to build a docker image for ogre using provided [Dockerfile](https://github.com/wavded/ogre/blob/master/Dockerfile). It doesn't seem helpful either. 
The 

> homme.gdal:v1.11.1

 doesn't get pulled completely. I tried to pull 

> latest 

tag. It works fine.
But again my confusion is does it install **gdal** or **ogre**?

How can i run this service on docker?

3)Overall, What would be the easier solution to **setup a local environment** to run **ogre** locally on a **windows** machine?

**Comment by wavded** [comment]
hey @nivemaham did you try this?

https://github.com/wavded/ogre/wiki/Running-Ogre-on-Windows

**Comment by nivemaham** [comment]
Hi @wavded , Thanks a lot. It helped. I was missing proper **gdal** installations guidelines.

**Comment by nivemaham** [comment]
Hi @wavded , this installation works, on Windows. 
Despite, i would like to build a docker image for this service. 
Currently available Dockerfile doesn't work. I tried with something like below,

```
FROM homme/gdal:latest
MAINTAINER Marc Harter <wavded@gmail.com

FROM node:6-onbuild
EXPOSE 3005 
```
I am running my service on 3005. Seems, the service is running. However i get 
`spawn ogr2ogr ENOENT Error.` when i try to convert a file
Since you mentioned in other posts, that you use `Docker` for ogre, could you advice how to run image of this service on Docker.

Nivethika

**Comment by wavded** [comment]
I haven't Docker on Windows, I usually use Docker just for development on my Mac.  That said, I want to get something more concrete for production but haven't thought about it enough.
