### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by diegolma** [wavded/ogre#58]
Hi, sometimes when i try to convert a .zip file with a shapefile inside i get this response:

{
error: true,
msg: "invalid signature: 0x8080014"
}

any ideas about how to resolve this error??

**Comment by wavded** [comment]
Haven't encountered this, I'm guessing something either wrong with the zip or the zip parser.  We use https://github.com/bower/decompress-zip.

**Comment by diegolma** [comment]
What version of the decompress-zip are you using?? and what parameters do you pass??

Thanks

**Comment by wavded** [comment]
That's in the ogr2ogr package, here:

https://github.com/wavded/ogr2ogr/blob/master/package.json#L27

**Comment by wavded** [comment]
Appears to be the be the default options: https://github.com/wavded/ogr2ogr/blob/master/lib/zip.js#L9

**Comment by madrev** [comment]
Hi there, I'm encountering the same error (with a different signature):
{"error":true,"msg":"invalid signature: 0xa"}

Any tips on how to get past this?
