### ISSUE TITLE
Conversion to meters instead of degrees

### ISSUE THREAD

**Issue by shabbirsafdar** [wavded/ogre#60]
I noticed when I did a conversion to geojson from a .shp file that I ended up with geojson in an amount that had to be in meters, since the coordinates were way too large to be in degrees.

Is there a way to request this conversion be output in degrees, or is that set in the .shp file?  There are too many points, and too great of a worry about inaccuracy to try doing a mathematical transformation on the resultant geojson.

**Comment by wavded** [comment]
There currently isn't a way to change the output conversion.  I believe it is determined by what is set in the `.shp` file.

**Comment by shabbirsafdar** [comment]
Thank you!  That's what I suspected.  Since I'm not an arcgis user myself, I've just asked the original file owner to send me a geojson in degrees, since that's what I needed.
