### ISSUE TITLE
JSON Post Request C# issue ({"error":true,"msg":"No json provided"})

### ISSUE THREAD

**Issue by livewirewarrior** [wavded/ogre#64]
I'm currently trying to use an HTTP POST Request to convert a GeoJSON to a shapefile but I keep getting the error message  {"error":true,"msg":"No json provided"}

My current code is as followed.

namespace ConsoleApplication4
{
    class Program
    {
        public static async Task<string> click1()
        {
            HttpClient client = new HttpClient(); // creates the client

            string jsonFileText = System.IO.File.ReadAllText(@"C:\Users\d14956\Desktop\map.json"); //reads from a geojson file

            HttpContent content = new System.Net.Http.StringContent("{\"json\": \"firstName\": \"John\" }", System.Text.Encoding.UTF8, "application/json");
            client.BaseAddress = new Uri("http://ogre.adc4gis.com/convertJson");
            var response = await client.PostAsync(client.BaseAddress,content);
            var fileStream = File.Create(@"C:\Users\d14956\Desktop\lol1.zip"); //creates files
            await response.Content.CopyToAsync(fileStream); // outputs content to file
            Console.WriteLine(await response.Content.ReadAsStringAsync());

            Console.ReadLine();
            return "";
        }

        public static void Main(string[] args)
        {
            string x = click1().Result;

        }
    }
}

**Comment by livewirewarrior** [comment]
@evermanwa

**Comment by livewirewarrior** [comment]
@evermanwa did you ever resolve this?

**Comment by evermanwa** [comment]
@livewirewarrior - Check my answer for the solution I came up with.

https://github.com/wavded/ogre/issues/54

**Comment by livewirewarrior** [comment]
@evermanwa  for prms.Add("json,json) is your json variable just a string that you read in?

**Comment by evermanwa** [comment]
Yes, all I had to do was read in the geojson as a string and it worked for
me. Are you receiving any errors?

**Comment by livewirewarrior** [comment]
@evermanwa how did you save the data that you should have received from OGRE? All I see is that you have the return method. I assume you saved it to a file?>

**Comment by evermanwa** [comment]
I will show you how I saved it when I get home. I actually saved it to a
stream, but you could save it to a file stream if you wanted

**Comment by livewirewarrior** [comment]
@evermanwa thanks It would help a lot to know how you read in the file and exported it.

**Comment by evermanwa** [comment]
`                    var jsonResponse = Encoding.UTF8.GetString(response);

                    jsonResponse = jsonResponse.Replace("0,null", "0");

                    byte[] zipFile = ExecuteShapeFileDownload(jsonResponse);`

**Comment by evermanwa** [comment]
Were you able to get your problem resolved?
