### ISSUE TITLE
Change dependency from Jade to Pug

### ISSUE THREAD

**Issue by dericke** [wavded/ogre#68]
`jade` has been renamed to `pug` and the old name deprecated. `jade` itself depends on deprecated packages. as well. Changing the dependency in `package.json` should resolve this, though I'm not sure if it may cause problems. According to the [package page](https://www.npmjs.com/package/pug), pug 2.x introduces breaking changes which should be investigated before making changes.

**Comment by wavded** [comment]
@dericke it does introduce some breaking changes but should be easy to solve especially since there isn't much jade to begin with.  I'd welcome a PR if you want to tackle it.

**Comment by wavded** [comment]
@dericke FYI: I found some time and went ahead and updated this as well as the other dependencies.

**Comment by dericke** [comment]
Great, thanks!
