### ISSUE TITLE
content-type

### ISSUE THREAD

**Issue by lcrumbliss** [wavded/ogre#75]
Hi there,

The content-type sent back from the webservice is always "application/zip".  It isn't normally an issue from most browsers, but for Safari iOS it seems to be; at least iOS 12.  I'm guessing it's a little more strict and if the indicated content-type doesn't actually match the content (for example, if it's CSV or KML in the response body) then iOS makes it just about impossible to do what you want with the response.

var data = "json=%7B%22type%22%3A%22FeatureCollection%22%2C%22features%22%3A%5B%7B%22type%22%3A%22Feature%22%2C%22geometry%22%3Anull%2C%22properties%22%3A%7B%22FID%22%3A%220%22%2C%22NAME%22%3A%22PITTSBURG%22%2C%22STATE%22%3A%2240%22%2C%22COUNTY%22%3A%22121%22%2C%22STATEPLANE%22%3A%22S%22%7D%2C%22id%22%3A0%7D%5D%7D&format=CSV&outputName=pc.csv";

var xhr = new XMLHttpRequest();

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", "https://ogre.adc4gis.com/convertJson");
xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
xhr.setRequestHeader("Accept", "text/csv");

xhr.send(data);

**Comment by lcrumbliss** [comment]
What about a switch statement returning the appropriate type depending on the output file type?

Shapefile (zip) is taken care of.  Maybe it would be possible to glean the the other types from [https://www.digipres.org/formats/mime-types//](url) and the ones not listed there can either default to text/plain or application/octet-stream depending.

That's the only way I can think of, really.

**Comment by wavded** [comment]
> What about a switch statement returning the appropriate type depending on the output file type?

The appropriate file type is unknown for most of the types, someone would have to figure out a mapping from every supported ogr2ogr format to a corresponding mime type. Since it is a data stream we can't detect the type based on extension for example.

**Comment by lcrumbliss** [comment]
Every ogr2ogr support format or just the subset supported by the ogre webservice?

**Comment by wavded** [comment]
The Ogre webservice would support whatever the underlying ogr2ogr tool supported which will vary depending on where it is hosted. There are some formats that won't work (like Postgres) because the web API doesn't allow for additional options.
