### ISSUE TITLE
Use ogre directly from another Script (without API)

### ISSUE THREAD

**Issue by maka1000** [wavded/ogre#81]
Hi, is it for using ogre required, that the tool is available with a domain as example www.apiogre.com, or is it also possible to use the features directly from another script on same server?

**Comment by vfonsecaz** [comment]
hi,

what do you mean? what are you trying to do?

**Comment by maka1000** [comment]
Hi,

I have an application on my server and i need to do requests to ogre which is on same server like the application. The usual way to use the api from ogre is this flow:
I send a JSON request to an URL (Domain/IP) and get a JSON respond:
[URL] --JSON-->[OGRE]--JSON-->

But I want to do this:
I send a JSON request directly to the ogre script (without the API and without the Domain/IP) and get a JSON respond:
[App] --JSON-->[OGRE]--JSON-->

**Comment by vfonsecaz** [comment]
Well in my case I installed ogre via npm so it's acessible via _http://localhost:3000_
Ogre has two endpoints:
_http://localhost:3000/convert_ (convert to geojson)
_http://localhost:3000/convertJson_ (convert to shapefile)

I have a web application (javascript) on the same server as ogre wich makes ajax calls to these ogre endpoints...
