### ISSUE TITLE
/convert endpoint broken

### ISSUE THREAD

**Issue by macrouch** [wavded/ogre#89]
Both on https://ogre.adc4gis.com/ and using the api call from an app returns the following 400 error when trying to use the `/convert` endpoint 

`{"error":true,"msg":"No file provided"}`

**Comment by abettermap** [comment]
I don't know enough about the changes otherwise I'd take a stab at a PR, but I'm guessing something to do with switching to `tmpdir` in the recent version change: https://github.com/wavded/ogre/compare/v2.0.1...v2.1.0

**Comment by macrouch** [comment]
`tmpdir` is only used in `/convertJson`, that endpoint seems to be working (at least on the website), my application doesn't use that endpoint, only `/convert`

I've been trying to get the code running locally since I filed the issue, I finally got it running but it works locally

**Comment by wavded** [comment]
This may have been due to a recently server upgrade to Node 14 LTS.  Do you still experience the issue now?  I currently cannot duplicate so I would need more details if you still have an issue.

**Comment by macrouch** [comment]
I switched my local environment to node 14 lts and it still works locally, but uploading any file to https://ogre.adc4gis.com/ fails

**Comment by rcr-usfs** [comment]
I am still getting this error: {"error":true,"msg":"No file provided"} when using the website as well as the api call. For now, I am just using the geojson and .zip version of the shapefile provided on the website.

**Comment by wavded** [comment]
Was able to duplicate now and applied a fix.  How does it perform now?

**Comment by macrouch** [comment]
https://github.com/expressjs/connect-multiparty/issues/29

Looks like connect-multiparty had an issue with Node 14 they fixed

**Comment by wavded** [comment]
@macrouch care to open a PR with that change?

**Comment by macrouch** [comment]
Already did ;)

It is also working for me with whatever change you made

**Comment by wavded** [comment]
Thx @macrouch for the PR and all ya'll for testing.

**Comment by macrouch** [comment]
Thanks for the quick response! Our users thank you!

**Comment by rcr-usfs** [comment]
Works for me now! Thank you!
