### ISSUE TITLE
Export to DGN

### ISSUE THREAD

**Issue by pelord** [wavded/ogre#94]
I try with postman to call your service (test purpose) to export a DGN and a DXF.
I have tried with a DXF with success. 
With the DGN. I get a file that could not be open into QGIS.

![image](https://user-images.githubusercontent.com/7397743/117980073-91f4a280-b301-11eb-855b-96210c0d4b9a.png)

I take the same features as on the website...

![image](https://user-images.githubusercontent.com/7397743/117980331-dd0eb580-b301-11eb-9d6b-e712ba1095e1.png)

**Comment by wavded** [comment]
Have you tried feeding that DGN back in and seeing if the GeoJSON matches?  If so, then I think Ogre is at least handling the conversion correct within itself.  I've heard of DGN issues with QGIS.

**Comment by pelord** [comment]
Ok. I try it.

**Comment by pelord** [comment]
I've used postman to export a DGN 

![image](https://user-images.githubusercontent.com/7397743/120219319-0c318c00-c209-11eb-83ea-d8396ac8e370.png)



I take the same dgn and import it from the web client

![image](https://user-images.githubusercontent.com/7397743/120219368-24091000-c209-11eb-82fb-7d0c1f72e290.png)


I get

{"errors":["FAILURE:","Unable to open datasource `/tmp/be4vPVzijLACWYOTq5matL5u.dgn' with the following drivers.","  -> PCIDSK","  -> netCDF","  -> JP2OpenJPEG","  -> PDF","  -> ESRI Shapefile","  -> MapInfo File","  -> UK .NTF","  -> OGR_SDTS","  -> S57","  -> DGN","  -> OGR_VRT","  -> REC","  -> Memory","  -> BNA","  -> CSV","  -> NAS","  -> GML","  -> GPX","  -> LIBKML","  -> KML","  -> GeoJSON","  -> Interlis 1","  -> Interlis 2","  -> OGR_GMT","  -> GPKG","  -> SQLite","  -> OGR_DODS","  -> ODBC","  -> WAsP","  -> PGeo","  -> MSSQLSpatial","  -> OGR_OGDI","  -> PostgreSQL","  -> MySQL","  -> OpenFileGDB","  -> XPlane","  -> DXF","  -> Geoconcept","  -> GeoRSS","  -> GPSTrackMaker","  -> VFK","  -> PGDUMP","  -> OSM","  -> GPSBabel","  -> SUA","  -> OpenAir","  -> OGR_PDS","  -> WFS","  -> HTF","  -> AeronavFAA","  -> Geomedia","  -> EDIGEO","  -> GFT","  -> SVG","  -> CouchDB","  -> Cloudant","  -> Idrisi","  -> ARCGEN","  -> SEGUKOOA","  -> SEGY","  -> XLS","  -> ODS","  -> XLSX","  -> ElasticSearch","  -> Walk","  -> Carto","  -> AmigoCloud","  -> SXF","  -> Selafin","  -> JML","  -> PLSCENES","  -> CSW","  -> VDV","  -> TIGER","  -> AVCBin","  -> AVCE00","  -> HTTP",""]}

**Comment by wavded** [comment]
I can confirm that GeoJSON to DGN is failing, DGN to GeoJSON seems to be fine.  I don't have a lot of time to peak at this ATM but would be open to PR if you wanted to look deeper.

**Comment by pelord** [comment]
I don't have the experience to work on a fix for this but if you have time & find it valuable to work on it, it's would be nice!

**Comment by wavded** [comment]
@pelord Ogre was recently upgraded. I am currently no longer getting an error when trying to convert to a DGN.  Can you test again?

**Comment by pelord** [comment]
I confirm the problem do not occur anymore! Thanks !
