### ISSUE TITLE
Stdout maxbuffer length exceeded while converting to geojson

### ISSUE THREAD

**Issue by skarthikeyan96** [wavded/ogre#97]
Problem: 

When we tried to convert kml file to geojson , we got response from the api stating `stdout maxbuffer length exceeded`. 

Expected Solution:

KML file should have been converted to geojson 

![image](https://user-images.githubusercontent.com/23126394/128006940-74c95ec4-a76e-4c2c-9571-d070031ac84d.png)

**Comment by wavded** [comment]
Looks like the limit is 200kb currently.  I'll see if we can bump that up.

**Comment by wavded** [comment]
This limit has been bumped up.  Reopen if still an issue.

**Comment by skarthikeyan96** [comment]
Awesome @wavded thank you
